### ISSUE TITLE
Extend responsive utilities

### ISSUE THREAD

**Issue by scriptex** [scriptex/itscss#78]
The responsive utilities located in `styles/utilities` folder should be extended to accommodate `flex` and `inline-flex` elements.

Something like this:
```scss
// Responsive Helpers
// scss-lint:disable ImportantRule

.visible-xs-block,
.visible-xs-inline,
.visible-xs-inline-block,
.visible-xs-inline-flex,
.visible-xs-flex,
.visible-sm-block,
.visible-sm-inline,
.visible-sm-inline-block,
.visible-sm-inline-flex,
.visible-sm-flex,
.visible-md-block,
.visible-md-inline,
.visible-md-inline-block,
.visible-md-inline-flex,
.visible-md-flex,
.visible-lg-block,
.visible-lg-inline,
.visible-lg-inline-block,
.visible-lg-inline-flex,
.visible-lg-flex {
	display: none !important;
}

@include mobile {
	.hidden-xs {
		display: none !important;
	}

	.visible-xs-block {
		display: block !important;
	}

	.visible-xs-inline {
		display: inline !important;
	}

	.visible-xs-inline-block {
		display: inline-block !important;
	}

	.visible-xs-inline-flex {
		display: inline-flex !important;
	}

	.visible-xs-flex {
		display: flex !important;
	}
}

@include tablet-portrait-only {
	.hidden-sm {
		display: none !important;
	}

	.visible-sm-block {
		display: block !important;
	}

	.visible-sm-inline {
		display: inline !important;
	}

	.visible-sm-inline-block {
		display: inline-block !important;
	}

	.visible-sm-inline-flex {
		display: inline-flex !important;
	}

	.visible-sm-flex {
		display: flex !important;
	}
}

@include tablet-landscape-only {
	.hidden-md {
		display: none !important;
	}

	.visible-md-block {
		display: block !important;
	}

	.visible-md-inline {
		display: inline !important;
	}

	.visible-md-inline-block {
		display: inline-block !important;
	}

	.visible-md-inline-flex {
		display: inline-flex !important;
	}

	.visible-md-flex {
		display: flex !important;
	}
}

@include desktop-only {
	.hidden-lg {
		display: none !important;
	}

	.visible-lg-block {
		display: block !important;
	}

	.visible-lg-inline {
		display: inline !important;
	}

	.visible-lg-inline-block {
		display: inline-block !important;
	}

	.visible-lg-inline-flex {
		display: inline-flex !important;
	}

	.visible-lg-flex {
		display: flex !important;
	}
}

```
